### ISSUE TITLE
홈브리지에 설치를 했는데 어떻게 정보를 넣고 수정하는지를 모르겠습니다

### ISSUE THREAD

**Issue by StephanieGordon13** [root500/homebridge-brunt-plug#1]
그리고 홈킷에서 스위치가 아닌 플러그로 보이게 설정하는 것도 가능하신가요?

**Comment by root500** [comment]
안녕하세요. 이슈 확인했습니다. 이 플러그인은 제가 오래전 단순히 개인적 사용 용도로 만들었던 패키지라 저도 리뷰 후에 정확한 답변이 가능할 것 같습니다. ^^;
먼저 정보 설정에 대해 간단히 답변드리자면 홈브릿지 설정파일인 config.json의 `platforms` 항목에서 `user`와 `password`라는 값으로 브런트 계정 정보를 추가하시면 사용 가능할 것 같습니다. 정확한건 제가 다시 테스트해보고 자세히 답변드리도록 하겠습니다.

**Comment by StephanieGordon13** [comment]
안녕하세요 하두 정신없이 보내서 이제야 수정하고 테스트를 해봤는데 오류가 나왔습니다.

Error: Device has no identifier yet, handshake needed
    at DeviceInfo.enrich (/homebridge/node_modules/homebridge-xiaomi-air-purifier3/node_modules/miio/lib/network.js:273:10)
    at Socket.<anonymous> (/homebridge/node_modules/homebridge-xiaomi-air-purifier3/node_modules/miio/lib/network.js:165:13)
    at Socket.emit (events.js:314:20)
    at UDP.onMessage (dgram.js:921:8)
    at Function.module.exports.loopWhile (/homebridge/node_modules/homebridge-brunt-plug/node_modules/deasync/index.js:71:23)
    at Function.sleep (/homebridge/node_modules/homebridge-brunt-plug/node_modules/deasync/index.js:41:18)
    at Plug.getServices (/homebridge/node_modules/homebridge-brunt-plug/dist/index.js:17479:26)
    at Server.createHAPAccessory (/usr/local/lib/node_modules/homebridge/src/server.ts:442:41)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:360:30
    at Array.forEach (<anonymous>)

위와 같았고...ㅠ 혹시 몰라서 로그 첨부할께요
감사합니다
[homebridge.log.txt](https://github.com/root500/homebridge-brunt-plug/files/5444352/homebridge.log.txt)

**Comment by simplenotezy** [comment]
@StephanieGordon13 havde you tried https://github.com/RobXYZ/homebridge-brunt#readme ?

**Comment by simplenotezy** [comment]
Oh, I see that's only for brunt plugs.

**Comment by jyhur805** [comment]
제  config.json에  아래와 같이 정보를 넣었는데 모듈이 로드 안되고 오류가 나오고 있습니다.
뭘 잘못한건지 모르겠습니다. ㅠ

`   "accessories": [
        {
            "name": "Mi Air2 Purifier",
            "enableAirQuality": true,
            "_bridge": {
                "username": "0E:B4:1E:CD:C0:79",
                "port": 34417
            },
            "accessory": "XiaomiMiAirPurifier"
        },
        {
            "accessory": "Brunt Plug",
            "name": "Brunt Plug",
            "user": "jyhur805@gmail.com",
            "pass": "%nln5VVM09Y-"
        }
    ],
    "platforms": [`

**Comment by jyhur805** [comment]
제 config.json에 아래와 같이 정보를 넣었는데 모듈이 로드 안되고 오류가 나오고 있습니다.
뭘 잘못한건지 모르겠습니다. ㅠ

>     "accessories": [
        {
            "name": "Mi Air2 Purifier",
            "enableAirQuality": true,
            "_bridge": {
                "username": "0E:B4:1E:CD:C0:79",
                "port": 34417
            },
            "accessory": "XiaomiMiAirPurifier"
        },
        {
            "accessory": "Brunt Plug",
            "name": "Brunt Plug",
            "user": "xxxxxxx@gmail.com",
            "pass": "xxxxxxxxxxx-"
        }
    ],
    "platforms": [

**Comment by root500** [comment]
@jyhur805 님 안녕하세요.
죄송합니다만 위에서 답변 드린 바와 같이 이 플러그인은 제가 오래전 개인사용 목적으로 개발했던 것으로, 다른 환경에서의 작동을 보장드릴 수 없는 상황입니다.
시기에 대해서 확답을 드리기는 어렵습니다만, 추후 시간 여유가 있을 때 작동에 대해 확인하고 답변을 드리고자 하오니, 혹시 오류 발생 시 오류 메시지 등 문제 파악을 위한 정보를 추가로 보내주시면 감사하겠습니다.

**Comment by jyhur805** [comment]
> @jyhur805 님 안녕하세요.
> 죄송합니다만 위에서 답변 드린 바와 같이 이 플러그인은 제가 오래전 개인사용 목적으로 개발했던 것으로, 다른 환경에서의 작동을 보장드릴 수 없는 상황입니다.
> 시기에 대해서 확답을 드리기는 어렵습니다만, 추후 시간 여유가 있을 때 작동에 대해 확인하고 답변을 드리고자 하오니, 혹시 오류 발생 시 오류 메시지 등 문제 파악을 위한 정보를 추가로 보내주시면 감사하겠습니다.

@root500님 안녕하세요 
답변 주셔서 감사합니다.
오류 로그를 일부 발췌 하여 첨부하였습니다.
이메일과 암호는 정확히 입력을 하였습니다. ㅠ
바쁘신데 시간 내어 주셔서 다시 한번 감사드립니다.

[homebridge_20210708.log](https://github.com/root500/homebridge-brunt-plug/files/6782483/homebridge_20210708.log)
