### ISSUE TITLE
Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.

### ISSUE THREAD

**Issue by simplenotezy** [root500/homebridge-brunt-plug#2]
I am getting the following error:

```
[Brunt Plug] start checking device...
[10/28/2020, 6:06:26 PM] Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:278:17)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:488:21
    at Array.forEach (<anonymous>)
    at Server.createHAPAccessory (/usr/local/lib/node_modules/homebridge/src/server.ts:477:16)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:360:30
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
[10/28/2020, 6:06:26 PM] Got SIGTERM, shutting down Homebridge...
[Brunt Plug] Brunt Plug (f5d4e5c7fc694554) - 226.4V 0A 0W 32°C
[Brunt Plug] Brunt Plug (f5d4e5c7fc694554) - 226.4V 0A 0W 32°C
[Brunt Plug] Brunt Plug (f5d4e5c7fc694554) - 226.2V 0A 0W 32°C
[Brunt Plug] Brunt Plug (f5d4e5c7fc694554) - 226.2V 0A 0W 32°C
```

Most likely because I have two devices on my Brunt account

**Comment by simplenotezy** [comment]
Deleting my other Brunt device solved the issue. This plugin only supports accounts with ONE brunt device

**Comment by rainbowicenow** [comment]
Hi, did you managed to get multiple devices work in the system?

**Comment by simplenotezy** [comment]
@rainbowicenow nope 😊 but I guess it should be simple enough to fix with a PR to this library
